import type { NextPage } from 'next';
import Head from 'next/head';
import { ChangeEvent, useState } from 'react';
import 'react-quill/dist/quill.snow.css';
import dynamic from 'next/dynamic';
import { ReactQuillProps } from 'react-quill';
import SaveButton from '../components/SaveButton';
import Title from '../components/Title';
import Navbar from '../components/Navbar';

const DynamicReactQuill = dynamic(() => import('react-quill'), { ssr: false });


const Home: NextPage = () => {
  const [saved, setSaved] = useState(false);
  const [title, setTitle] = useState('');
  const [value, setvalue] = useState('');

  const toolbarOptions = [
    [{ 'header': [1, 2, 3, 4, 5, 6, false] }],
    [{ 'font': [] }],
    ['bold', 'italic', 'underline'],
    ['blockquote', 'code-block'],
    ['link', 'image']
  ];

  const reactQuillProps: ReactQuillProps = {
    value: value,
    onChange: setvalue,
    modules: {
      toolbar: toolbarOptions
    }
  } 

  const handleTitleChange = (e: ChangeEvent<HTMLInputElement>): void => {
    setSaved(false);
    setTitle(e.currentTarget.value);
  }

  return (
    <div>
      <Head>
        <title>Papyr.it</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='flex flex-col items-center w-full h-screen bg-[#EAE5D3]'>
        <Navbar />
        
        <div className='flex items-center justify-center h-full'>
          <div className='w-[816px] space-y-10 bg-[#f3eed9] p-10 rounded-xl h-5/6 min-h-fit'>
            
            <div className='flex items-center space-x-5 text-3xl font-bold'>
              <Title title={title} setTitle={handleTitleChange} />
              <SaveButton saved={saved} setSaved={setSaved} />
            </div>

            <DynamicReactQuill {...reactQuillProps} className='h-[70%]' id='editor'></DynamicReactQuill>
          </div>
        </div>

      </main>
    </div>
  );
}

export default Home
