import type { NextPage } from 'next';
import Head from 'next/head';
import { useState } from 'react';
import 'react-quill/dist/quill.snow.css';
import dynamic from 'next/dynamic';
import { ReactQuillProps } from 'react-quill';

const DynamicReactQuill = dynamic(() => import('react-quill'), { ssr: false });


const Home: NextPage = () => {
  const [value, setvalue] = useState('');

  const toolbarOptions = [
    [{ 'header': [1, 2, 3, 4, 5, 6, false] }],
    [{ 'font': [] }],
    ['bold', 'italic', 'underline'],
    ['blockquote', 'code-block'],
    ['link', 'image']
  ];

  const reactQuillProps: ReactQuillProps = {
    value: value,
    onChange: setvalue,
    modules: {
      toolbar: toolbarOptions
    }
  } 

  return (
    <div>
      <Head>
        <title>Papyr.it</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='flex flex-col items-center w-full h-screen bg-[#EAE5D3]'>
        <nav className='bg-zinc-800 p-2 text-center w-full'>
          <h1 className='text-xl text-zinc-100'>Papyr.it</h1>
        </nav>
        
        <div className='w-[816px]'>
          <DynamicReactQuill {...reactQuillProps}></DynamicReactQuill>
        </div>

      </main>
    </div>
  );
}

export default Home
